import { PI_STALL_INSTRUCTION, type PiClient, type PiPosture } from '../pi/PiClient.js';
import type { PiResearchClient } from '../pi/PiResearchClient.js';
import { log } from '../logger.js';
import { ReasoningSpeechAssembler } from './ReasoningSpeechAssembler.js';
import { ResearchPartAssembler, researchPartLimits } from './ResearchPartAssembler.js';
import { D2_RECHECK_MS, D2_STALL_MARGIN_MS, type RuntimeBudget } from './RuntimeBudget.js';
import type {
  ActiveResponse,
  HostEventPayload,
  HostEventType,
  Scheduler,
  SpeechOutputPort,
  SpeechOutputStream,
  SpeechSynthesisStart,
} from './SessionOrchestrator.js';

export interface MultiPartPart {
  partIndex: number;
  kind: 'stall' | 'body';
  speechStream?: SpeechOutputStream;
  playbackId?: string;
  assistantText?: string;
  generatedSamples: number;
  terminal: boolean;
  started: boolean;
  /** Latency-budget instrumentation only; never drives pipeline behavior. */
  firstAppendAtMs?: number;
  sampleRate?: number;
  modelKey?: string;
}

/**
 * Narrow callback surface from a MultiPartResponse into its owning
 * SessionOrchestrator. The orchestrator keeps ownership of the event envelope,
 * playback ledgers, provisional barge-in state, and session phases; the
 * response machine drives its own part lifecycle through these hooks.
 */
export interface MultiPartResponseHost {
  readonly sessionId: string;
  readonly pi: PiClient;
  readonly speech: Pick<SpeechOutputPort, 'begin' | 'pause' | 'release' | 'cancel'>;
  readonly idFactory: () => string;
  readonly now: () => number;
  readonly scheduler: Scheduler;
  /** Optional per-session latency budget; every use is fail-soft and measurement-only. */
  readonly budget?: RuntimeBudget;
  emit<T extends HostEventType>(type: T, payload: HostEventPayload<T>): void;
  /** True while this response is still the registered multi-part machine of a live session. */
  isCurrent(response: MultiPartResponse): boolean;
  isUserSpeaking(): boolean;
  hasProvisional(responseId: string): boolean;
  beginProvisionalBargeIn(responseId: string): boolean;
  enterPlaying(): void;
  openLedger(playbackId: string, outputEpoch: number, generatedSamples: number): void;
  advanceLedger(playbackId: string, outputEpoch: number, generatedSamples: number): void;
  /** Returns false when the ledger is missing, superseded, or already terminal. */
  setLedgerSamples(playbackId: string, outputEpoch: number, generatedSamples: number): boolean;
  markLedgerTerminal(playbackId: string): void;
  addAssistantContext(text: string): void;
  /** Orchestrator's recoverable failure broadcast for a failed response. */
  failResponse(reasonCode: 'reasoning_unavailable' | 'reasoning_invalid' | 'tts_failed'): void;
  /** Unregister this response from the orchestrator's active/multi-part slots. */
  detach(response: MultiPartResponse): void;
  /** Transition the session back to listening and broadcast the state. */
  settleListening(): void;
}

function validOffset(value: number): boolean {
  return Number.isSafeInteger(value) && value >= 0;
}
function truncateUtf8(value: string, maxBytes: number): string {
  const bytes = Buffer.from(value, 'utf8');
  if (bytes.length <= maxBytes) return value;
  let end = maxBytes;
  while (end > 0 && (bytes[end]! & 0xc0) === 0x80) end--;
  return bytes.subarray(0, end).toString('utf8');
}

/**
 * Multi-part turn machine: a fast no-tool stall (part 0) followed by research
 * body parts (indices 1-7) generated by the research Pi child and played in
 * order. Extracted from SessionOrchestrator; enabled only when multiPartEnabled
 * and a research client are configured, otherwise handleStableFinal keeps the
 * single-part path unchanged.
 */
export class MultiPartResponse {
  readonly responseId: string;
  readonly turnId: string;
  readonly epoch: number;
  readonly posture: PiPosture;
  readonly controller = new AbortController();
  readonly parentActive: ActiveResponse;
  readonly parts: MultiPartPart[] = [];
  readonly partByPlayback = new Map<string, MultiPartPart>();
  cancelled = false;
  private researchDone = false;
  private readonly transcript: string;
  private bodyStartedAtMs: number | undefined;
  private bodyFirstReleased = false;
  private stallHandoffFired = false;
  private stallHandoffTimer: (() => void) | undefined;

  constructor(
    private readonly host: MultiPartResponseHost,
    turn: { epoch: number; turnId: string; text: string; posture: PiPosture },
    private readonly boundedContext: string,
    private readonly researchPi: PiResearchClient,
  ) {
    this.transcript = truncateUtf8(turn.text, 16 * 1024);
    this.responseId = host.idFactory();
    this.turnId = turn.turnId;
    this.epoch = turn.epoch;
    this.posture = turn.posture;
    // The parent active response shares this machine's controller so an epoch
    // bump on the orchestrator side cancels every outstanding part stream.
    this.parentActive = {
      responseId: this.responseId,
      turnId: turn.turnId,
      epoch: turn.epoch,
      posture: turn.posture,
      controller: this.controller,
      cancelled: false,
      reasoningPrefix: '',
      generatedSamples: 0,
    };
  }

  async run(): Promise<void> {
    try {
      // ---- Part 0: stall (existing 45-word no-tool path) ----
      const stall: MultiPartPart = {
        partIndex: 0,
        kind: 'stall',
        generatedSamples: 0,
        terminal: false,
        started: false,
      };
      this.parts.push(stall);
      const stallInstruction = this.stallInstruction();
      const stallStartedAt = this.now();
      let stallFirstDeltaAtMs: number | undefined;
      log('session', `part started stall 0 ${this.responseId}`);
      this.host.emit('response.part_started', {
        turnId: this.turnId,
        responseId: this.responseId,
        partIndex: 0,
        kind: 'stall',
      });
      this.host.emit('reasoning.started', {
        turnId: this.turnId,
        responseId: this.responseId,
        posture: this.posture,
        partIndex: 0,
      });
      const stallStream = this.host.speech.begin({
        sessionId: this.host.sessionId,
        epoch: this.epoch,
        responseId: this.responseId,
        partIndex: 0,
        signal: this.controller.signal,
        onGeneratedSamples: (total) => this.recordPartSamples(stall, total),
      });
      stall.speechStream = stallStream;
      void stallStream.started.catch(() => undefined);
      stallStream.started.then(
        (meta) => {
          if (this.host.isCurrent(this)) this.attachPartTts(stall, meta);
        },
        () => {
          if (this.host.isCurrent(this)) this.failMultiPart(0, 'tts_failed');
        },
      );
      const stallAssembler = new ReasoningSpeechAssembler(this.posture);
      let stallFinalText: string | undefined;
      let stallRequestFailed = false;
      let emittedStallPreview = '';
      const emitStallPreview = (text: string): void => {
        if (!text || text === emittedStallPreview || !this.host.isCurrent(this)) return;
        emittedStallPreview = text;
        this.host.emit('reasoning.delta', { turnId: this.turnId, responseId: this.responseId, partIndex: 0, text });
      };
      for await (const event of this.host.pi.request(
        {
          posture: this.posture,
          transcript: this.transcript,
          boundedContext: this.boundedContext,
          maxWords: 45,
          instruction: stallInstruction,
        },
        this.controller.signal,
      )) {
        if (!this.isCurrent()) return;
        if (event.type === 'final') stallFinalText = event.text;
        else if (event.type === 'delta') {
          if (stallFirstDeltaAtMs === undefined) {
            stallFirstDeltaAtMs = this.now();
            this.host.budget?.observeStallFirstDelta(Math.max(0, stallFirstDeltaAtMs - stallStartedAt));
          }
          for (const chunk of stallAssembler.append(event.text)) {
            this.noteFirstAppend(stall);
            stallStream.append(chunk.text);
          }
          const preview = stallAssembler.canonicalPrefix;
          if (preview) emitStallPreview(preview);
        } else if (event.type === 'error') {
          stallRequestFailed = true;
          break;
        }
      }
      if (!this.isCurrent()) return;
      let stallText: string | undefined;
      if (!stallRequestFailed) {
        try {
          const finalized = stallAssembler.final(stallFinalText ?? '');
          stallText = finalized.result.canonical;
          if (finalized.tail) {
            this.noteFirstAppend(stall);
            stallStream.append(finalized.tail.text);
          }
          if (!stallText || stallText.split(/\s+/u).filter(Boolean).length > 45) stallText = undefined;
          if (this.posture === 'question' && (stallText?.match(/\?/gu) ?? []).length > 1) stallText = undefined;
          if (stallText && /^(?:```|\{|\[|assistant\s*:|system\s*:|<\/?(?:script|iframe)\b)/iu.test(stallText))
            stallText = undefined;
        } catch {
          stallText = undefined;
        }
      }
      if (!stallText) {
        // Fail-soft: chunks released by append() were already streamed to the
        // stall TTS and are valid by construction (each passed isValidChunk), so
        // keep that streamed prefix as the stall instead of failing the turn.
        const streamedText = stallAssembler.emittedText();
        if (streamedText) stallText = streamedText;
      }
      if (!stallText) {
        this.failMultiPart(0, stallRequestFailed ? 'reasoning_unavailable' : 'reasoning_invalid');
        return;
      }
      stall.assistantText = stallText;
      this.parentActive.reasoningPrefix = stallText;
      this.host.emit('reasoning.final', {
        turnId: this.turnId,
        responseId: this.responseId,
        posture: this.posture,
        partIndex: 0,
        text: stallText,
      });
      this.host.budget?.observeStallText(Math.max(0, this.now() - stallStartedAt));
      this.host.budget?.registerPart({
        responseId: this.responseId,
        turnId: this.turnId,
        partIndex: 0,
        ...(stall.firstAppendAtMs !== undefined ? { openedAtMs: stall.firstAppendAtMs } : {}),
        words: this.wordCount(stallText),
      });
      stallStream.finish();
      log('session', `part final stall 0 ${this.responseId} ${stallText.length}chars ${this.now() - stallStartedAt}ms`);
      this.host.emit('response.part_final', {
        turnId: this.turnId,
        responseId: this.responseId,
        partIndex: 0,
        kind: 'stall',
      });
      if (!this.isCurrent()) return;

      // ---- Body parts from the research Pi child ----
      this.bodyStartedAtMs = this.now();
      this.checkStallHandoff();
      this.armStallHandoffRecheck();
      const bodyLimits = researchPartLimits(this.posture);
      const bodyAssembler = new ResearchPartAssembler(
        bodyLimits.maxPartWords,
        bodyLimits.maxPartChars,
        bodyLimits.maxPartSentences,
        bodyLimits.maxParts,
      );
      for await (const event of this.researchPi.requestBody(
        {
          posture: this.posture,
          transcript: this.transcript,
          boundedContext: this.boundedContext,
          stallText,
          onToolActivity: (activity) => {
            // Concise tool-call visibility for this turn only; dropped once the
            // response is no longer current so cancelled turns stay quiet.
            if (!this.isCurrent()) return;
            this.host.emit('tool.activity', {
              scope: 'turn',
              turnId: this.turnId,
              responseId: this.responseId,
              ...activity,
            });
          },
        },
        this.controller.signal,
      )) {
        if (!this.isCurrent()) return;
        if (event.type === 'final') {
          try {
            const finalized = bodyAssembler.final(event.text);
            for (const part of finalized.parts) this.startBodyPart(part);
            this.researchDone = true;
          } catch {
            this.failMultiPart(Math.max(1, this.parts.length), 'reasoning_invalid');
            return;
          }
          this.completeMultiPartIfReady();
        } else if (event.type === 'delta') {
          try {
            for (const part of bodyAssembler.append(event.text)) this.startBodyPart(part);
          } catch {
            this.failMultiPart(Math.max(1, this.parts.length), 'reasoning_invalid');
            return;
          }
        } else if (event.type === 'error') {
          this.failMultiPart(Math.max(1, this.parts.length), 'reasoning_unavailable');
          return;
        }
      }
      if (!this.isCurrent()) return;
      this.researchDone = true;
      this.completeMultiPartIfReady();
    } catch {
      if (this.isCurrent()) this.failMultiPart(0, 'reasoning_unavailable');
    }
  }

  /**
   * Playback terminal for one of this machine's parts. Returns true when the
   * playback id belonged to a still-open part and completion was evaluated;
   * false lets the orchestrator fall through to its single-part handling.
   */
  notePlaybackStopped(playbackId: string): boolean {
    const part = this.partByPlayback.get(playbackId);
    if (!part || part.terminal) return false;
    if (part.partIndex === 0) this.clearStallHandoffTimer();
    part.terminal = true;
    this.completeMultiPartIfReady();
    return true;
  }

  private isCurrent(): boolean {
    return this.host.isCurrent(this);
  }

  private now(): number {
    return this.host.now();
  }

  private wordCount(text: string): number {
    return text.split(/\s+/u).filter(Boolean).length;
  }

  private noteFirstAppend(part: MultiPartPart): void {
    if (part.firstAppendAtMs === undefined) part.firstAppendAtMs = this.now();
  }

  /**
   * D1 adaptive stall sizing: append a target-word hint to the unchanged
   * stall instruction. Fail-soft — any budget trouble falls back to the bare
   * instruction; the 45-word hard cap and byte bound are enforced elsewhere
   * and stay untouched here.
   */
  private stallInstruction(): string {
    const budget = this.host.budget;
    if (!budget) return PI_STALL_INSTRUCTION;
    try {
      const hint = budget.stallTargetHint();
      this.host.emit('budget.mitigation', budget.stallTargetFinding(this.turnId, this.responseId));
      return `${PI_STALL_INSTRUCTION}\n${hint}`;
    } catch {
      return PI_STALL_INSTRUCTION;
    }
  }

  /** D2 measurement-only check: is the body part 1 ETA cutting it too close to the stall end? */
  private checkStallHandoff(): void {
    const budget = this.host.budget;
    if (!budget || this.stallHandoffFired || this.bodyStartedAtMs === undefined) return;
    const stall = this.parts[0];
    if (!stall?.playbackId) return;
    const remainingMs = budget.playbackRemainingMs(stall.playbackId);
    if (remainingMs === undefined) return;
    const elapsedMs = Math.max(0, this.now() - this.bodyStartedAtMs);
    if (!budget.stallHandoffAtRisk(remainingMs, elapsedMs)) return;
    this.stallHandoffFired = true;
    this.clearStallHandoffTimer();
    const estimates = budget.estimatesSnapshot();
    const bodyEtaMs = budget.bodyEtaMs(elapsedMs);
    this.host.emit('budget.mitigation', {
      turnId: this.turnId,
      responseId: this.responseId,
      kind: 'late_handoff_projected',
      partIndex: 1,
      detail: {
        estimates,
        trigger: `bodyEta ${Math.round(bodyEtaMs)}ms + ttsTtfa ${Math.round(estimates.ttsTtfaMs)}ms > stallRemaining ${Math.round(remainingMs)}ms - ${D2_STALL_MARGIN_MS}ms`,
      },
    });
  }

  private armStallHandoffRecheck(): void {
    if (!this.host.budget) return;
    const tick = (): void => {
      this.stallHandoffTimer = undefined;
      if (!this.isCurrent() || this.stallHandoffFired || this.bodyFirstReleased) return;
      this.checkStallHandoff();
      if (!this.stallHandoffFired && this.isCurrent() && !this.bodyFirstReleased)
        this.stallHandoffTimer = this.host.scheduler.schedule(D2_RECHECK_MS, tick);
    };
    this.stallHandoffTimer = this.host.scheduler.schedule(D2_RECHECK_MS, tick);
  }

  private clearStallHandoffTimer(): void {
    this.stallHandoffTimer?.();
    this.stallHandoffTimer = undefined;
  }

  private recordPartSamples(part: MultiPartPart, total: number): void {
    if (!validOffset(total) || total < part.generatedSamples || this.cancelled) return;
    part.generatedSamples = total;
    if (!part.playbackId) return;
    this.host.budget?.notePlaybackSamples(part.playbackId, total);
    this.host.advanceLedger(part.playbackId, this.epoch, total);
  }

  private attachPartTts(part: MultiPartPart, meta: SpeechSynthesisStart): void {
    if (!Number.isSafeInteger(meta.sampleRate) || meta.sampleRate <= 0) {
      this.failMultiPart(part.partIndex, 'tts_failed');
      return;
    }
    if (
      meta.generatedSamples !== undefined &&
      (!Number.isSafeInteger(meta.generatedSamples) || meta.generatedSamples <= 0)
    ) {
      this.failMultiPart(part.partIndex, 'tts_failed');
      return;
    }
    part.playbackId = meta.playbackId;
    part.started = true;
    part.sampleRate = meta.sampleRate;
    part.modelKey = `${meta.backendId ?? 'unknown'}/${meta.modelId ?? 'default'}`;
    this.partByPlayback.set(meta.playbackId, part);
    if (this.host.budget) {
      if (part.firstAppendAtMs !== undefined)
        this.host.budget.observeTtsTtfa(Math.max(0, this.now() - part.firstAppendAtMs), part.modelKey);
      this.host.budget.attachPlayback({
        responseId: this.responseId,
        turnId: this.turnId,
        partIndex: part.partIndex,
        playbackId: meta.playbackId,
        sampleRate: meta.sampleRate,
        generatedSamples: part.generatedSamples,
      });
    }
    this.host.openLedger(meta.playbackId, this.epoch, Math.max(part.generatedSamples, meta.generatedSamples ?? 0));
    this.host.emit('tts.started', {
      responseId: this.responseId,
      playbackId: meta.playbackId,
      sampleRate: meta.sampleRate,
      ...(meta.backendId ? { backendId: meta.backendId } : {}),
      ...(meta.modelId ? { modelId: meta.modelId } : {}),
      partIndex: part.partIndex,
      ...(meta.outputStreamId !== undefined ? { outputStreamId: meta.outputStreamId } : {}),
    });
    // Callers guard with isCurrent(), so the parent active response is this
    // machine's parent; mirror the first audible part onto it for response-level lifecycle.
    if (!this.parentActive.playbackId) this.parentActive.playbackId = meta.playbackId;
    this.host.enterPlaying();
    // Apply the same speech-before-TTS guard to prefetched multipart parts.
    // The first part may become audible after VAD has already seized the mic.
    if (this.host.isUserSpeaking() && !this.host.hasProvisional(this.responseId))
      this.host.beginProvisionalBargeIn(this.responseId);
    else if (this.host.hasProvisional(this.responseId)) this.host.speech.pause(this.responseId);
    this.host.speech.release?.(this.responseId, part.partIndex);
    if (meta.completion) {
      void meta.completion.then(
        (completed) => {
          if (!this.isCurrent()) return;
          if (!Number.isSafeInteger(completed.generatedSamples) || completed.generatedSamples <= 0) {
            this.failMultiPart(part.partIndex, 'tts_failed');
            return;
          }
          if (!this.host.setLedgerSamples(meta.playbackId, this.epoch, completed.generatedSamples)) return;
          if (this.host.budget) {
            this.host.budget.notePlaybackSamples(meta.playbackId, completed.generatedSamples);
            const audioSeconds = part.sampleRate ? completed.generatedSamples / part.sampleRate : 0;
            if (part.firstAppendAtMs !== undefined && audioSeconds > 0)
              this.host.budget.observeTtsRtf(
                Math.max(0, this.now() - part.firstAppendAtMs) / 1000 / audioSeconds,
                part.modelKey,
              );
          }
          this.host.emit('tts.ended', {
            responseId: this.responseId,
            playbackId: meta.playbackId,
            generatedSamples: completed.generatedSamples,
            partIndex: part.partIndex,
          });
        },
        () => {
          if (this.isCurrent()) this.failMultiPart(part.partIndex, 'tts_failed');
        },
      );
    }
  }

  private startBodyPart(chunk: { text: string; partIndex: number }): void {
    if (chunk.partIndex > 7) {
      this.failMultiPart(chunk.partIndex, 'reasoning_invalid');
      return;
    }
    const part: MultiPartPart = {
      partIndex: chunk.partIndex,
      kind: 'body',
      generatedSamples: 0,
      terminal: false,
      started: false,
    };
    this.parts.push(part);
    if (!this.bodyFirstReleased) {
      this.bodyFirstReleased = true;
      if (this.bodyStartedAtMs !== undefined)
        this.host.budget?.observeBodyFirstPart(Math.max(0, this.now() - this.bodyStartedAtMs));
    }
    if (this.host.budget) {
      this.host.budget.registerPart({
        responseId: this.responseId,
        turnId: this.turnId,
        partIndex: chunk.partIndex,
        openedAtMs: this.now(),
        words: this.wordCount(chunk.text),
      });
      for (const finding of this.host.budget.handoffCheckOnRelease({
        responseId: this.responseId,
        turnId: this.turnId,
        partIndex: chunk.partIndex,
      }))
        this.host.emit('budget.mitigation', finding);
    }
    const partStartedAt = this.now();
    log('session', `part started body ${chunk.partIndex} ${this.responseId}`);
    this.host.emit('response.part_started', {
      turnId: this.turnId,
      responseId: this.responseId,
      partIndex: chunk.partIndex,
      kind: 'body',
    });
    this.host.emit('reasoning.started', {
      turnId: this.turnId,
      responseId: this.responseId,
      posture: this.posture,
      partIndex: chunk.partIndex,
    });
    const stream = this.host.speech.begin({
      sessionId: this.host.sessionId,
      epoch: this.epoch,
      responseId: this.responseId,
      partIndex: chunk.partIndex,
      signal: this.controller.signal,
      onGeneratedSamples: (total) => this.recordPartSamples(part, total),
    });
    part.speechStream = stream;
    void stream.started.catch(() => undefined);
    stream.started.then(
      (meta) => {
        if (this.isCurrent()) this.attachPartTts(part, meta);
      },
      () => {
        if (this.isCurrent()) this.failMultiPart(part.partIndex, 'tts_failed');
      },
    );
    this.noteFirstAppend(part);
    stream.append(chunk.text);
    part.assistantText = chunk.text;
    this.host.emit('reasoning.delta', {
      turnId: this.turnId,
      responseId: this.responseId,
      partIndex: chunk.partIndex,
      text: chunk.text,
    });
    this.host.emit('reasoning.final', {
      turnId: this.turnId,
      responseId: this.responseId,
      posture: this.posture,
      partIndex: chunk.partIndex,
      text: chunk.text,
    });
    stream.finish();
    log(
      'session',
      `part final body ${chunk.partIndex} ${this.responseId} ${chunk.text.length}chars ${this.now() - partStartedAt}ms`,
    );
    this.host.emit('response.part_final', {
      turnId: this.turnId,
      responseId: this.responseId,
      partIndex: chunk.partIndex,
      kind: 'body',
    });
  }

  private completeMultiPartIfReady(): void {
    if (!this.researchDone || this.parts.some((part) => !part.terminal)) return;
    this.finishMultiPart(true);
  }

  private finishMultiPart(addContext: boolean): void {
    if (this.cancelled) return;
    this.cancelled = true;
    this.clearStallHandoffTimer();
    this.host.budget?.endTurn(this.responseId);
    const parentText = this.parts
      .map((part) => part.assistantText)
      .filter(Boolean)
      .join(' ')
      .trim();
    if (addContext && parentText) this.host.addAssistantContext(parentText);
    this.host.detach(this);
    this.host.settleListening();
  }

  failMultiPart(partIndex: number, reasonCode: 'reasoning_unavailable' | 'reasoning_invalid' | 'tts_failed'): void {
    log('session', `multipart fail reason=${reasonCode} partIndex=${partIndex} responseId=${this.responseId}`);
    this.host.emit('response.failed', { turnId: this.turnId, responseId: this.responseId, reasonCode, partIndex });
    this.host.failResponse(reasonCode);
    this.cancelMultiPart();
  }

  private cancelMultiPart(): void {
    if (this.cancelled) return;
    this.cancelled = true;
    this.clearStallHandoffTimer();
    this.host.budget?.endTurn(this.responseId);
    this.controller.abort();
    this.host.speech.cancel(this.responseId);
    for (const part of this.parts) {
      if (part.playbackId) this.host.markLedgerTerminal(part.playbackId);
    }
    this.host.detach(this);
    this.host.settleListening();
  }
}
