"""Generate one strict Pydantic model for every canonical owned JSON schema."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_ROOT = ROOT / "packages/contracts/schema"
OUT = ROOT / "services/audio/src/generated/contracts.py"
INIT = OUT.parent / "__init__.py"

schemas = [
    (path.relative_to(SCHEMA_ROOT).as_posix(), json.loads(path.read_text()))
    for path in sorted(SCHEMA_ROOT.rglob("*.json"))
]
classes = "\n\n".join(
    f'''class {schema["title"]}(CanonicalModel):
    schema_path: ClassVar[str] = {path!r}'''
    for path, schema in schemas
)
schema_json = json.dumps(dict(schemas), sort_keys=True, separators=(",", ":"))
content = f'''# Generated by scripts/generate_contracts.py. Do not edit.
import json
from typing import Any, ClassVar

from jsonschema import Draft202012Validator, FormatChecker, ValidationError, validators
from pydantic import RootModel, model_validator
from referencing import Registry, Resource

PROTOCOL_VERSION = 1
CONTRACT_SCHEMAS: dict[str, dict[str, Any]] = json.loads({schema_json!r})
_REGISTRY = Registry().with_resources(
    (schema["$id"], Resource.from_contents(schema)) for schema in CONTRACT_SCHEMAS.values()
)

def _max_utf8_bytes(validator: Any, limit: int, value: Any, schema: dict[str, Any]):
    del validator, schema
    if not isinstance(value, str):
        return
    try:
        encoded = value.encode("utf-8", errors="strict")
    except UnicodeEncodeError:
        yield ValidationError("string contains an unpaired UTF-16 surrogate")
        return
    if len(encoded) > limit:
        yield ValidationError(f"{{value!r}} exceeds {{limit}} UTF-8 bytes")

Utf8Draft202012Validator = validators.extend(
    Draft202012Validator, {{"maxUtf8Bytes": _max_utf8_bytes}}
)

class CanonicalModel(RootModel[dict[str, Any]]):
    schema_path: ClassVar[str]

    @model_validator(mode="before")
    @classmethod
    def validate_canonical_schema(cls, value: Any) -> Any:
        validator = Utf8Draft202012Validator(
            CONTRACT_SCHEMAS[cls.schema_path],
            registry=_REGISTRY,
            format_checker=FormatChecker(),
        )
        errors = sorted(validator.iter_errors(value), key=lambda error: list(error.path))
        if errors:
            raise ValueError("; ".join(error.message for error in errors))
        return value

{classes}
'''
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(content)
names = [schema["title"] for _, schema in schemas]
INIT.write_text(
    "# Generated by scripts/generate_contracts.py. Do not edit.\n"
    "from . import contracts\n"
    f"from .contracts import {', '.join(names)}\n\n"
    f"__all__ = {['contracts', *names]!r}\n"
)
